export const variants = {
  ctaButton: "cta",
  primaryButton: "primary",
  secondaryButton: "secondary",
  outlineDarkButton: "outlineDark",
  outlineLiteButton: "outlineLite",
  ghostButton: "ghost",
  positiveToastMessage: "positive",
  negativeToastMessage: "negative",
  warningToastMessage: "warning",
  textInput: "text",
  numberInput: "number",
  approvedMessage: "approved",
  feedbackMessage: "feedback",
  errorInlineMessage: "error",
  infoInlineMessage: "info",
  warningInlineMessage: "warning",
  infoMessage: "info",
  successMessage: "success",
  errorMessage: "error",
  warningMessage: "warning",
  timeOutMessage: "timeout",
};
